Use -rf flag in rm command
sdelements/shtdlib pull request #89
Opened 2021-05-28 19:00 UTC by madhavmalhotra-3089

For mac, `rm --force` does not work. Hence using `rm -rf`.

2021-05-28 19:04 UTC, hrpatel requested changes

2021-05-28 19:04 UTC, hrpatel commented on shtdlib.sh
> +        if rm -Rf "${custom_ssh_auth_socket_path}" ; then
We don't need the `-R` do we?

2021-05-28 19:05 UTC, madhavmalhotra-3089 commented on shtdlib.sh
> +        if rm -Rf "${custom_ssh_auth_socket_path}" ; then
updated

2021-05-31 14:53 UTC, hrpatel approved these changes

2021-05-31 14:54 UTC, merged